from flask import Flask, jsonify
from flask_cors import CORS
import pickle
import os
import numpy as np

app = Flask(__name__)
CORS(app) # Allows Flutter to communicate with this server

HISTORY_FILE = "history.pkl"

def load_history():
    """Reads the pickle file generated by your mqtt_sub.py"""
    if not os.path.exists(HISTORY_FILE):
        return []
    
    try:
        with open(HISTORY_FILE, "rb") as f:
            data = pickle.load(f)
            # Handle if data is a deque or list
            return list(data) if data else []
    except Exception as e:
        print(f"Error loading history: {e}")
        return []

@app.route('/api/live-data', methods=['GET'])
def get_live_data():
    history = load_history()
    
    if not history:
        return jsonify({"error": "No data available", "data": []})

    # Get the latest entry for current status
    latest = history[-1]
    
    # Extract only health scores for the chart (last 20 points)
    # Your backend calculates health between 0.0 and 1.0
    health_trend = [entry['health'] for entry in history[-20:]]

    # Structure the JSON for Flutter
    response = {
        "status": "online",
        "latest_timestamp": latest.get('timestamp'),
        
        # Metrics mapped from your backend logic
        "current_health": round(latest.get('health', 0) * 100, 1), # Convert 0-1 to %
        "anomaly_score": round(latest.get('anomaly', 0), 2),
        "machine_status": latest.get('status', 'UNKNOWN'),
        
        # Historical data for the graph
        "health_history": health_trend,
        
        # Full logs for the list view (reversed to show newest first)
        "logs": history[-10:][::-1] 
    }
    
    return jsonify(response)

if __name__ == '__main__':
    # Run on all interfaces so emulator can see it
    app.run(host='0.0.0.0', port=5000, debug=True)